"""Generates the push-notification texts from tool/l10n/strings.py, so a push
reads exactly like the same notification in the app's list:

  supabase/functions/_shared/push_strings.json   (send-push Edge Function)
  android/app/src/main/res/values*/push_strings.xml  (notification channel name)

    python tool/l10n/build_push_l10n.py
"""
import json
import os
import sys
from xml.sax.saxutils import escape

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from strings import LANGS, S  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# notification_type (DB enum) -> the app's Activity string for it.
TYPES = {
    "new_follower": "activityNewFollower",
    "new_review": "activityNewReview",
    "ad_this": "activityAdThis",
    "review_reply": "activityReviewReply",
    "mention": "activityMention",
    "sold_milestone": "activitySoldMilestone",
    "sold_milestone_first": "activitySoldFirst",
    "gag_milestone": "activityGagMilestone",
}

out = {t: {lang: S[key][lang] for lang in LANGS} for t, key in TYPES.items()}
for t, texts in out.items():
    for lang, text in texts.items():
        wanted = "{count}" if t in ("sold_milestone", "gag_milestone") else None if t.endswith("_first") else "{actor}"
        if wanted and wanted not in text:
            sys.exit(f"{t} [{lang}] lost its {wanted} placeholder")
path = os.path.join(ROOT, "supabase", "functions", "_shared", "push_strings.json")
with open(path, "w", encoding="utf-8", newline="\n") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)
    f.write("\n")

# Android resource folders: "in" is Android's own code for Indonesian.
FOLDER = {"en": "values", "id": "values-in"}
res = os.path.join(ROOT, "android", "app", "src", "main", "res")
for lang in LANGS:
    folder = os.path.join(res, FOLDER.get(lang, f"values-{lang}"))
    os.makedirs(folder, exist_ok=True)
    name = escape(S["pushChannelName"][lang]).replace("'", "\\'")
    with open(os.path.join(folder, "push_strings.xml"), "w", encoding="utf-8", newline="\n") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tool/l10n/build_push_l10n.py. -->\n')
        f.write(f'<resources>\n    <string name="push_channel_name">{name}</string>\n</resources>\n')
print(f"{len(TYPES)} push texts and the channel name x {len(LANGS)} languages")
