// send-push
//
// Called by the database (0024_push_notifications.sql: a pg_net request from
// the notifications INSERT trigger) with {"notification_id": "..."} and the
// shared secret in x-push-secret. Sends that notification to every device
// of its recipient through FCM (Android + iOS), in the language each device
// registered with — the same wording as the app's Notifications list
// (_shared/push_strings.json, generated by tool/l10n/build_push_l10n.py).
//
// Respects notification_preferences (no row = everything on). Tokens FCM
// reports as gone are deleted. Idempotency: one notification row = one call
// (pg_net doesn't retry), so nothing extra is needed.
//
// Required secrets: PUSH_WEBHOOK_SECRET (same value as the Vault secret
// push_webhook_secret), FIREBASE_SERVICE_ACCOUNT (service account JSON).

import { createClient } from "npm:@supabase/supabase-js@2";
import strings from "../_shared/push_strings.json" with { type: "json" };
import { readServiceAccount, sendFcm } from "../_shared/fcm.ts";

type NotificationType = Exclude<keyof typeof strings, "sold_milestone_first">;

// notification_type -> notification_preferences column.
const PREFERENCE: Record<NotificationType, string> = {
  new_follower: "new_followers",
  new_review: "reviews",
  review_reply: "reviews",
  mention: "mentions",
  ad_this: "ad_this",
  sold_milestone: "milestones",
  gag_milestone: "milestones",
};

Deno.serve(async (req: Request) => {
  try {
    if (req.method !== "POST") return json({ error: "METHOD_NOT_ALLOWED" }, 405);

    const expected = Deno.env.get("PUSH_WEBHOOK_SECRET");
    if (!expected || !safeEqual(req.headers.get("x-push-secret") ?? "", expected)) {
      return json({ error: "UNAUTHORIZED" }, 401);
    }

    let notificationId: unknown;
    try {
      notificationId = (await req.json())?.notification_id;
    } catch {
      return json({ error: "INVALID_REQUEST" }, 400);
    }
    if (typeof notificationId !== "string") return json({ error: "INVALID_REQUEST" }, 400);

    const sa = readServiceAccount();
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!sa || !supabaseUrl || !serviceRoleKey) return json({ error: "CONFIG_MISSING" }, 500);
    const db = createClient(supabaseUrl, serviceRoleKey);

    const { data: n, error: nError } = await db
      .from("notifications")
      .select("id, recipient_id, type, payload, actor:profiles!notifications_actor_id_fkey(username)")
      .eq("id", notificationId)
      .maybeSingle();
    if (nError) return json({ error: "DB_ERROR", detail: nError.message }, 500);
    if (!n) return json({ skipped: "NOT_FOUND" });

    const type = n.type as NotificationType;
    if (!(type in PREFERENCE)) return json({ skipped: "UNKNOWN_TYPE" });

    const { data: prefs } = await db
      .from("notification_preferences")
      .select("*")
      .eq("user_id", n.recipient_id)
      .maybeSingle();
    if (prefs && prefs[PREFERENCE[type]] === false) return json({ skipped: "PREFERENCE_OFF" });

    const { data: tokens, error: tError } = await db
      .from("device_tokens")
      .select("id, token, platform, locale")
      .eq("user_id", n.recipient_id);
    if (tError) return json({ error: "DB_ERROR", detail: tError.message }, 500);
    if (!tokens || tokens.length === 0) return json({ skipped: "NO_DEVICES" });

    const payload = (n.payload ?? {}) as Record<string, unknown>;
    // deno-lint-ignore no-explicit-any
    const actorUsername = ((n as any).actor?.username as string | undefined) ?? null;
    const actor = actorUsername ? `@${actorUsername}` : "AdGag";

    // Reviews/replies/mentions: the review text as the second line.
    let excerpt: string | null = null;
    if (typeof payload.comment_id === "string") {
      const { data: c } = await db.from("comments").select("body").eq("id", payload.comment_id).maybeSingle();
      if (c?.body) excerpt = truncate(String(c.body), 140);
    }

    const data: Record<string, string> = { notification_id: n.id, type };
    if (typeof payload.ad_id === "string") data.ad_id = payload.ad_id;
    if (actorUsername) data.actor_username = actorUsername;

    // Milestones: "{count}" in the text; the very first SOLD has its own line.
    const count = typeof payload.count === "number" ? payload.count : null;
    const textKey = type === "sold_milestone" && count === 1 ? "sold_milestone_first" : type;

    let sent = 0;
    const gone: string[] = [];
    for (const device of tokens) {
      const texts = strings[textKey] as Record<string, string>;
      const lang = (device.locale ?? "en").split(/[-_]/)[0];
      const title = (texts[lang] ?? texts.en)
        .replace("{actor}", actor)
        .replace("{count}", count === null ? "" : count.toLocaleString(lang));
      const notification: Record<string, string> = { title };
      if (excerpt) notification.body = excerpt;
      const result = await sendFcm(sa, {
        token: device.token,
        notification,
        data,
        android: {
          priority: "HIGH",
          notification: { channel_id: "adgag_activity" },
        },
        apns: {
          headers: { "apns-priority": "10" },
          payload: { aps: { sound: "default", "thread-id": type } },
        },
      });
      if (result.ok) {
        sent++;
      } else if (result.unregistered) {
        gone.push(device.id);
      } else {
        console.error(`FCM send failed for token ${device.id}: ${result.status} ${result.detail}`);
      }
    }
    if (gone.length > 0) await db.from("device_tokens").delete().in("id", gone);

    return json({ sent, removed: gone.length });
  } catch (e) {
    console.error("send-push unexpected error", e);
    return json({ error: "UNEXPECTED_ERROR" }, 500);
  }
});

function truncate(s: string, max: number): string {
  const t = s.replace(/\s+/g, " ").trim();
  return t.length <= max ? t : `${t.slice(0, max - 1)}…`;
}

function safeEqual(a: string, b: string): boolean {
  const x = new TextEncoder().encode(a);
  const y = new TextEncoder().encode(b);
  if (x.length !== y.length) return false;
  let diff = 0;
  for (let i = 0; i < x.length; i++) diff |= x[i] ^ y[i];
  return diff === 0;
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
}
